// Centralized company configuration (EN)
export const COMPANY_CONFIG = {
  name: 'InzaiQ LLC',
  tagline: 'InzaiQ – Innovation in Automation and SaaS for digital businesses',

  heroDescription: `At InzaiQ we help companies and entrepreneurs scale their businesses with AI-powered SaaS solutions. We offer automation tools, content generation, and other digital services designed to save time and maximize results.

Automation, optimization, scalability, and reliable support: that is our approach to driving your growth.

We do not follow trends: we solve them. We build systems that understand context and anticipate what is coming. This way your company evolves without friction.

Technology with purpose. Results with direction.`,

  contact: {
    email: 'support@inzaiq.com',
    phone: '+595 976 147913',
    address: 'Registered Agents Inc, 30 N Gould St Ste R, Sheridan, WY 82801',
  },

  socialLinks: [
    { name: 'LinkedIn', url: 'https://linkedin.com/company/inzaiq', icon: 'LinkedIn' },
    { name: 'Twitter', url: 'https://twitter.com/inzaiq', icon: 'Twitter' },
    { name: 'Instagram', url: 'https://instagram.com/inzaiq', icon: 'Instagram' },
    { name: 'GitHub', url: 'https://github.com/inzaiq', icon: 'GitHub' },
  ],

  navigation: [
    { title: 'Home', href: '#home' },
    { title: 'About', href: '#about' },
    { title: 'Products', href: '#products' },
    { title: 'Services', href: '#services' },
    { title: 'Contact', href: '#contact' },
  ],

  about: {
    title: 'Who We Are',
    description: `At InzaiQ, we turn ideas into technology solutions that power the future.
    We are specialists in artificial intelligence and automation, creating tools that not only solve today’s problems,
    but also anticipate tomorrow’s needs.`,
    features: [
      { title: 'Relentless Innovation', description: 'We build cutting-edge technology that makes a real market difference.', icon: 'Innovation' },
      { title: 'Intelligent Solutions', description: 'Our AI tools adapt and evolve with your business needs.', icon: 'Psychology' },
      { title: 'Seamless Integration', description: 'We design systems that integrate into your existing infrastructure without friction.', icon: 'Integration' },
    ],
  },

  services: [
    { title: 'Custom AI Development', description: 'We build AI solutions tailored to your company’s specific needs.', icon: 'SmartToy' },
    { title: 'Process Automation', description: 'We optimize and automate business processes to boost efficiency and reduce costs.', icon: 'AutoMode' },
    { title: 'Systems Integration', description: 'We connect and synchronize platforms to create a cohesive technology ecosystem.', icon: 'Hub' },
    { title: 'Technology Consulting', description: 'We advise on implementing emerging technologies to keep you ahead.', icon: 'Lightbulb' },
    { title: 'Data Analytics', description: 'We turn data into actionable insights via advanced analytics and machine learning.', icon: 'Analytics' },
    { title: 'Support and Maintenance', description: 'We provide ongoing support and updates to ensure optimal performance.', icon: 'Support' },
  ],
};

export const PRODUCTS_CONFIG = [
  {
    id: 'product-cards-generator',
    name: 'ProdifyQ - E‑commerce Listing Generator',
    category: 'Content and Automation',
    description: 'Create high performing product listings for any eCommerce platform. SEO-optimized AI Powered Automatic Listing Generator web tool trained for Amazon\'s A9 Algorithm.',
    shortDescription: 'High performing listings generated with AI',
    url: 'https://prodifyq.com',
    features: [
      { title: 'SEO descriptions', description: 'Search-optimized text with configurable tone.', icon: 'Description' },
      { title: 'Automatic bullets', description: 'Key points generated by category and attributes.', icon: 'Checklist' },
      { title: 'CSV export', description: 'Ready for Shopify, WooCommerce, VTEX and more.', icon: 'Upload' },
    ],
    benefits: [
      'Reduce catalog creation time',
      'Increase CTR and conversion',
      'Standardize content quality',
    ],
    status: 'available',
    featured: true,
  },
  {
    id: 'data-analytics',
    name: 'Data Analytics Platform',
    category: 'Analytics',
    description: 'Turn your data into actionable insights with our AI‑powered analytics platform.',
    shortDescription: 'Advanced AI analytics for decision making',
    features: [
      { title: 'Advanced Visualization', description: 'Interactive dashboards and real-time visualizations.', icon: 'BarChart' },
      { title: 'AI Predictions', description: 'Predictive models to anticipate trends and behavior.', icon: 'TrendingUp' },
      { title: 'Data Integration', description: 'Connect multiple data sources into one platform.', icon: 'Storage' },
    ],
    benefits: [
      'Data-driven decisions',
      'Accurate predictions',
      'Measurable ROI',
      'Automated reporting',
    ],
    technologies: ['Python', 'TensorFlow', 'Apache Spark', 'Power BI'],
    status: 'coming-soon',
    featured: false,
  },
];

export const SEO_CONFIG = {
  title: 'InzaiQ - Where innovation takes shape',
  description: 'InzaiQ turns technology into solutions that think, adapt, and move with you. We build AI tools that automate with precision and scale intelligently.',
  keywords: 'artificial intelligence, automation, AI, machine learning, InzaiQ, technology innovation, business solutions',
  author: 'InzaiQ',
  url: 'https://inzaiq.com',
  image: '/og-image.png',
};


